
# This code was originally written by Josh Shapiro and Candace Savonen
# for the Childhood Cancer Data Lab, an initiative of Alexs Lemonade Stand Foundation.
# https://github.com/AlexsLemonade/refinebio-examples/blob/33cdeff66d57f9fe8ee4fcb5156aea4ac2dce07f/.github/workflows/style-and-sp-check.yml#L1

# Adapted for this jhudsl repository by Candace Savonen Apr 2021

name: Build, Render, and Push

# Controls when the action will run. Triggers the workflow on push
# events only for the master branch
on:
  push:
    branches: [ main ]
    paths:
      - '**.Rmd'
      - docker/Dockerfile

jobs:
  # This workflow contains a single job called "build-all"
  build-all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          # get the full repo
          fetch-depth: 0
          # use github PAT
          token: ${{ secrets.GIT_TOKEN }}


      # Run bookdown rendering
      - name: Run bookdown render
        run: |
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          jhudsl/course_template \
          Rscript -e "bookdown::render_book('index.Rmd')"

      # Commit the rendered bookdown files
      - name: Commit rendered bookdown files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Render bookdown' || echo "No changes to commit"
          git push origin main || echo "No changes to push"

